### ISSUE TITLE
There is no Run, Apps, and window icon (missing icon)

### ISSUE THREAD

**Issue by AntiHeadacheGuy** [catppuccin/rofi#1]
Hello. When I applied the theme and launch rofi to see the effects, I got the problem that 3 icons in bottom (Run, Apps, window) is missing and looks like this:
![2022-02-20T12:02:40,537025605+07:00](https://user-images.githubusercontent.com/91181632/154829086-89d61fc1-aa67-4a69-9d26-02b9b5841e9a.png)
I use Arch Linux so I think I'm missing the fonts for the icons. So how can I get the Run, Apps, and window icon to show properly in rofi ?

**Comment by AntiHeadacheGuy** [comment]
Fixed this myself by installing ttf-nerd-fonts-symbols. Closing this issue

**Comment by AlphaTechnolog** [comment]
I will add this instructions later to the `README.md` sorry for it :D

Thank you for use the catppuccin theme for rofi :)

**Comment by citosid** [comment]
I have installed ttf-nerd-symbols font but still shows the wrong icons:

![image](https://github.com/catppuccin/rofi/assets/201430/0f42d5fa-5dc1-4e67-963a-56b4ad87ceb4)
